name: craftr-build
modulename: craftr
version: 5.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: General purpose build system with an easy to use API and DSL.
url: https://github.com/craftr-build/craftr
license: MIT
typed: true
requirements:
- python ^3.8
- astor ^0.8.1
- dataclasses ^0.6
- nr.caching ^0.3.2
- nr.functional ^0.1.0
- nr.parsing.core ^2.0.2
- nr.preconditions ^0.0.4
- nr.pylang.ast ~0.0.5
- termcolor ^1.1.0
- typing-extensions ^3.10.0.0
test-drivers:
- type: mypy
- type: pytest
test-requirements:
- types-termcolor
