[tool.yapf]
BASED_ON_STYLE = "pep8"
ALIGN_CLOSING_BRACKET_WITH_VISUAL_INDENT = true
ALLOW_MULTILINE_LAMBDAS = true
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = true
BLANK_LINE_BEFORE_MODULE_DOCSTRING = true
BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION = 2
COALESCE_BRACKETS = true
CONTINUATION_ALIGN_STYLE = "VALIGN-RIGHT"
CONTINUATION_INDENT_WIDTH = 2
DEDENT_CLOSING_BRACKETS = true
INDENT_CLOSING_BRACKETS = false
