# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ 5.x ]
    tags: [ '*' ]
  pull_request:
    branches: [ 5.x ]

jobs:

  run-craftr-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.x']
        example: [ 'hello_world.py' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Craftr
      run: python -m pip install -e .
    - name: Run example
      run: python craftr-core/examples/${{ matrix.example }}
